### ISSUE TITLE
String \x escape difference to jq

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#129]
Hi, i just noticed that gojq supports \x escape but not jq, not sure if intentional or accidental? the unescape seems to happen in the lexer when calling `strconv.Unquote`. Personally i wish jq would support it also but i guess there might be issues with invalid code points?

```
$ jq --version
jq-1.6-139-ga9ce724
$ jq -n '"\xff"'
jq: error: Invalid escape at line 1, column 4 (while parsing '"\x"') at <top-level>, line 1:
"\xff"
jq: 1 compile error

$ gojq -n '"\xff" | ., length, utf8bytelength'
"\ufffd"
1
1
```

Should be documented maybe?

**Comment by itchyny** [comment]
Undocumented feature extensions are all experimental and may be dropped in the future. Using these features is okay but can be removed due to jq compatibility. The features or bug fixes listed in the differences section are unlikely to be dropped. In this sense, I don't want to list this escape differences in README.md.

**Comment by wader** [comment]
Yeap makes sense 👍

**Comment by itchyny** [comment]
I was thinking about the invalid code points. gojq deals with binary data as string and that's why the combination of base64d format + raw output flag works well, and `gojq -sRrj .` does not modify the input stream. But on marshaling to output, or `tojson`, `explode`, it uses `\ufffd` ([`REPLACEMENT CHARACTER`](https://en.wikipedia.org/wiki/Specials_(Unicode_block))), for invalid code points. I can't find any other reasonable solution because there is no way to represent binary data in JSON, which only allows Unicode characters.

**Comment by wader** [comment]
Seem resonable i think, i can't come up with any alternative solution either.
 
jq master seems to do the same on reading invalid utf-8
```
$ echo -ne '\xff' | jq -R explode
[
  65533
]
```
