### ISSUE TITLE
Why is there no --arg and --argjson option?

### ISSUE THREAD

**Issue by kawaz** [itchyny/gojq#15]
Without the --arg option, it is difficult to safely pass strings from outside to gpjq queries. Why not?

**Comment by itchyny** [comment]
--arg is already implemented in #10

**Comment by kawaz** [comment]
I'm sorry that the confirmation is not thorough. I only checked --help for v0.7.0 installed by homebrew.
After building master, it was usable without any problem.

Thank you very much.

**Comment by itchyny** [comment]
I'm considering creating a new release after fixing some reported bugs so please wait. Also note that the syntax is different from jq, because (I believe) the go-flags library does not allow multiple argument for one flag like `--arg name value`. Although I accepted the `--arg name=value` patch, I'll look for the way to make it more compatible.

**Comment by kawaz** [comment]
I've understood. Thanks,

**Comment by itchyny** [comment]
I implemented --arg and --argjson which is completely (I believe) compatible with jq. I'll release 0.8.0 in a few days.
