### ISSUE TITLE
Behaves differently with jq regarding precedence of try

### ISSUE THREAD

**Issue by MiSawa** [itchyny/gojq#157]
In `jq`, it seems to be that many expression inside try block, if not all, are required to be parenthesized. For example, if `jq` sees a `*` between `try` and `catch`, it throws a compilation error where `gojq` accepts it.
```sh
$ jq -n 'try . * . catch .'
jq: error: syntax error, unexpected catch, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
try . * . catch .
jq: 1 compile error
$ gojq -n 'try . * . catch .'
"cannot multiply: null and null"
```
Furthermore, if the `catch` part is missing, `jq` and `gojq` both accepts the query but the created parse tree seems to be different.
```sh
$ jq -n 'try error("a"), .'     # treated as (try error("a")), .
null
$ gojq -n 'try error("a"), .'   # treated as try (error("a"), .)
$ jq --version
jq-1.6
$ gojq --version
gojq 0.12.6 (rev: HEAD/go1.17.6)
```

**Comment by itchyny** [comment]
The original motivation I remember is to make more queries acceptable in try statements than jq, as I thought using parenthesis in a query like the first example is very annoying because there is no syntax ambiguity. But precedence issue like the second example, or even with arithmetic operators (`try 0 * error(0)`) is considered as a bug in gojq. I fixed this.
