### ISSUE TITLE
Invalid values for float32 types & modification of data

### ISSUE THREAD

**Issue by kzantow** [itchyny/gojq#179]
It appears there is [a normalization process](https://github.com/itchyny/gojq/blob/main/normalize.go#L69) which takes, among other things, `float32` values and casts them to `float64`. This results in invalid data being returned. This _also_ is updating the original data structure passed to the function. I put an example together here, which should print a value of `1.5094385` but instead is printing a value with more data:

```go
func Test_float32(t *testing.T) {
	input := map[string]interface{}{
		"value": float32(1.5094385),
	}
	fmt.Printf("%s %v\n", reflect.TypeOf(input["value"]).Name(), input["value"])
	query, _ := gojq.Parse(".value")
	code, _ := gojq.Compile(query)
	iter := code.Run(input)
	v, ok := iter.Next()
	if ok {
		fmt.Printf("value: %v\n", v)
	}
	fmt.Printf("%s %v\n", reflect.TypeOf(input["value"]).Name(), input["value"])
}
```

Outputs:
```
=== RUN   Test_float32
float32 1.5094385
value: 1.5094385147094727
float64 1.5094385147094727
```

I believe this should be respecting `float32` values and ideally not updating the provided data structure.

**Comment by itchyny** [comment]
Note that `gojq` does not handle types except for what can appear in JSON unmarshalization into `any` (=`interface{}`) type. For example, [`gojq.TypeOf`](https://github.com/itchyny/gojq/blob/v0.12.8/type.go#L8-L30), which is used to implement the `type` filter, panics on `float32`, etc. For mathematical filters, the `sin` filter is using [`math.Sin`](https://pkg.go.dev/math#Sin) only defined for `float64`. The normalization process is the best effort to handle numbers to what gojq can process, and delaying the process makes implementation quite a mess. Therefore, this is an expected behavior of `gojq`, you cannot expect `gojq` to retain the `float32` type.

**Comment by kzantow** [comment]
Thank you for the quick response and clarification.
