### ISSUE TITLE
cli: Expose Run with args and IO streams

### ISSUE THREAD

**Issue by abhinav** [itchyny/gojq#181]
cli.Run currently uses os.Args, os.Stdout, os.Stdin, and os.Stderr.

It would be helpful to be able to invoke cli.Run with custom values for all of these
when you need an application that emulates some of jq's flags without replicating them all.

This could be accomplished with an API similar to the following:

```go
package cli

type Config struct {
        // If Stdin is nil, an empty stdin will be used.
        // If Stdout or Stderr are nil, that output stream will be discarded.
        Stdin  io.Reader
        Stdout io.Writer
        Stderr io.Writer
}

func (cfg *Config) Run(args []string) (exitCode int)
```

This is basically a subset of the existing `cli` type and its functionality exposed in a more controlled manner.

**Comment by itchyny** [comment]
The cli package is implemented for the gojq command itself, so I don't implement the package for library users. For example, the package changes the behavior due to environment variables and files in the local filesystem, which is often inappropriate for library users. Also, the package is goroutine unsafe, it writes and reads package private variables. Moreover, the `cli#run` function does not accept a Context, so the program embedding the package will stuck with a query something like `repeat(0)`. The `gojq` package is designed to be embedded so provides a way to interrupt the execution. So in my opinion, trying to embed the cli package is a really bad idea, in most case you will likely want to use only the subset of it.

**Comment by abhinav** [comment]
Oh, that makes sense. I was trying to avoid mirroring the command line flags for jq. 

My use case a bit absurd. 
I have a very large shell script that relies heavily on jq. 
I don't want to rewrite it wholesale. 
My intent was to embed the shell script into a Go program, use https://github.com/mvdan/sh to run it, and use gojq to excise the dependency on the jq CLI. 

But given all the concerns you raised, my suggestion doesn't apply anyway. I'll find a different route. 

Thanks for the fast response!
