### ISSUE TITLE
Inability to provide user-defined indexing funtion

### ISSUE THREAD

**Issue by xakepp35** [itchyny/gojq#208]
## Problem:

In `func.go` code we have `func funcIndex2(_, v, x interface{}) interface{}` which plays important role in data accessing mechanism.
There are several cases, when you may need to override it, eg when:

- need to work with alternative serialization library, which uses []byte as its backend and custom data accessor functions, to avoid use slow marshals/unmarshals
- want to perform object wrapping and provide custom metadata functions, "builtins", that way you may provide an input not as a map[string]interface{} but as a map[string]CustomDataAccessor where custom data accessors may have a data + normally "invisible" metadata

these possibilities are completely blocked without vendor code modification, because original `funcIndex` is hardcoded and unexported, and compiler/executor doesnt support providing user-defined override

## Proposed solution for reads:

i am offering small change, allowing to override it with fully custom logi, alongside with being able to freely reuse it. At least globally, renaming funcIndex2 to DefaultFuncIndex2, so package user will be able to override it in his side freely at will:

```
var funcIndex2 = DefaultFuncIndex2

func SetCustomFuncIndex2(newFuncIndex2 func(a, v, x interface{}) interface{}) {
	funcIndex2 = newFuncIndex2
}

func DefaultFuncIndex2(_, v, x interface{}) interface{} {
```

This will  allow at least read-only access, requiring minimal code modification and shouldn't affect performance or break anything.

## More advanced solution

Seriously, we want to ask you if we can establish that in a better manner. It is about to start having an interfaces set, like json or msgpack libraries have for their extensibility - they check, "if current object X satisfies interface" - they invoke it rather than doing something default:

```
// Marshaler is the interface implemented by types that
// can marshal themselves into valid JSON.
type Marshaler interface {
	MarshalJSON() ([]byte, error)
}
```

Same way, with your jq data processing package, - here its a wish to have something from following Property*** or Jq*** family:

```
interface PropertyGetter {
	// mimics map getter - fetches and returns property value by key
	// ok can be used to test if key exists, or index is within slice bounds, because we cannot rely on default value to determine that
	PropertyGet(key interface{}) (val interface{}, ok bool)
}

interface PropertySetter {
	// upserts property value to the key
	PropertySet(key, val interface{})
}

interface PropertyDeleter {
	// removes property from map by key
	PropertyDel(key interface{})
}

// optional, task-specific, for completeness of illustration
interface PropertyPopper {
	// acts as atomic get+del in 1 call, with return value thus simulation atomic "pop" operation
	PropertyPop(key interface{}) (val interface{}, ok bool)
}

// optional, task-specific, for completeness of illustration
interface PropertyCleaner {
	// removes all properties from the object
	PropertyClean()
}
```

Doing typeasserts if `x` is one of following (depending on context) alongside of and then falling back to default operation mode will allow extremely flexible and overridable operation. Sincerely; Awaiting your feedback!

**Comment by itchyny** [comment]
This is a part of the feature request for supporting custom types, right? Previously I have posted some thoughts on this topic here https://github.com/itchyny/gojq/issues/153#issuecomment-1002212920. The jq language contains various queries not just indexing, but slicing, mapping, flattening, getting length and type, binary operators, etc. These operations glows the gojq interfaces messy. And since jq is not just for JSON querying but for JSON construction, we need to consider how to provide the way to construct instances of custom types. Also, if gojq provides interfaces to make structs queryable with gojq, someone may send pull requests to random Go projects to make their public types comfortable to use with gojq. That's not what I hope. So as written in README.md, convert to the standard type using marshal and unmarshal back.

**Comment by wader** [comment]
To add to what @itchyny said. [fq](https://github.com/wader/fq) maintain gojq fork at https://github.com/wader/gojq/commits/fq with various changes, the "Add JQValue interface to support custom values" change might be interesting and sounds similar to what your looking for.
Current it's limited to read-only, it used to have methods for updating also but it turned out quite complicated for an implementor to reproduce all of jq's behaviours, but probably not impossible. Instead now it shallowly converts the JQValue into standard gojq value and then uses the standard gojq update code. If you want to use part of it i would probably recommend doing your own fork as things might change, but i'm happy to answer questions and try to keep implementations in sync if possible.

**Comment by xakepp35** [comment]
@itchyny Why not fully defining your operations set as interfaces, in order to being able to integrate with package easily. Of course, operations should include construction of objects, flattening, slicing, whatever. And its not about requiring use it - it may continue work as it was with default types, but just being able to override it externally (eg if you dont know the type, but it satisfies your interface for operation - try run it, instead of forcibly failing with error unknown type)

@wader that can be helpful but in the end we need writing parts as well, but having single interface may be a problem. You need to split interface same way as json.Marshaller and json.Unmarshaller does. eg what if you want to do custom logic only on read, or only on write? it shouldnt be single monolithic interface, but a set of interfaces, suited for different parts, that way it may be very bery friendly for implementor!

**Comment by itchyny** [comment]
Listing _all_ the jq operations is quite hard; that list will include all the mathematical filters (for example someone may propose their own custom matrix type to be applied to `exp`), and it makes the gojq APIs quite a mess. I cannot maintain such APIs as stable features. I think using the standard types is a good communication between gojq and libraries, considering the maintenance cost I can pay for this package. But this package is open source, feel free to fork and add APIs just as fq is doing.

**Comment by wader** [comment]
@xakepp35 Yes true the current JQValue interface is quite big, could probably be split up somewhat and be improved. The set of methods it has now is the result of trial and error trying to combine how to model a jq value that fits what fq meeds but also not leak fq details into it, so for example what functions/operations are "special", `type`, `tonumber`, slicing, should values be shallowly iteratable/indexable so they can return another JQValue? and also how to keep the changes maintainable with the gojq implementation.
