### ISSUE TITLE
Make available via conda-forge

### ISSUE THREAD

**Issue by corneliusroemer** [itchyny/gojq#261]
Would be great to have gojq installable via conda-forge.

There's a third-party build available already (except for linux-aarch64) from @danielnachun: https://anaconda.org/dnachun/gojq

Reason for using gojq over jq in my case would be that jq has a limited depth limit (see https://stackoverflow.com/questions/75524357/how-to-increase-depth-limit-of-jq)

**Comment by itchyny** [comment]
If there is already a package which is up to date, that's enough, isn't it?

**Comment by danielnachun** [comment]
Just clarify this, the reason I will submit it to conda-forge is because there is better build infrastructure on their CI system than I have on the one I set up - i.e. support for Windows and Linux architectures not supported by GitHub Actions, as well as automatic updates and more.  I'm already planning to submit the package to conda-forge so this should hopefully be resolved in the next few days.

**Comment by corneliusroemer** [comment]
Thanks a lot @danielnachun!

> If there is already a package which is up to date, that's enough, isn't it?

Few reasons why it's best to have it in conda-forge rather than some third-party channel:
- Bus factor >1
- Transparency/Reproducibility, I trust @danielnachun and am happy to use his binary but others might not
- Third-party channels need to be added explicitly, and one might not want to do this
