### ISSUE TITLE
add is slower then jq's version

### ISSUE THREAD

**Issue by LeonB** [itchyny/gojq#33]
``` sh
$ time cat faker.txt | jq 'length'
14927

real	0m0,161s
user	0m0,157s
sys	0m0,013s
```

``` sh
$ time cat faker.txt | gojq 'length'
14927

real	0m0,135s
user	0m0,144s
sys	0m0,034s
```

``` sh
 time cat faker.txt | jq 'add' > /dev/null

real	0m0,286s
user	0m0,284s
sys	0m0,009s
```

``` sh
 time cat faker.txt | gojq 'add' > /dev/null

real	0m31,324s
user	0m46,734s
sys	0m0,245s
```

[faker.txt](https://github.com/itchyny/gojq/files/4691978/faker.txt)

**Comment by itchyny** [comment]
Thanks for reporting and I fixed this issue by implementing `add` by an internal function. I'm facing the difficulty due to the implementation difference of objects in jq and gojq. While jq extends an object without modifying the original but gojq should shallow-copy each time because we can't extend a Go `map[string]interface{}` without modifying the original. So _improving performance_ of this kind of cases leads to growing the complexity of internal functions. But considering the performance penalty (and how the function is useful), it is still worth fixing.
