### ISSUE TITLE
Parse/render YAML and other formats

### ISSUE THREAD

**Issue by teoincontatto** [itchyny/gojq#45]
Support to parse and render [YAML](https://yaml.org/) format would be a very big plus if compared to jq project that is [having difficulties in implementing it and probably will never do](https://github.com/stedolan/jq/issues/467).

A good example of what I have in mind is the [yq python wrapper to jq](https://github.com/kislyuk/yq) but with some extra parameters options to trigger the YAML parser instead of JSON (or maybe just a translator).

Parsing/rendering of other formats like XML, [TOML](https://github.com/toml-lang/toml), [HCL](https://github.com/hashicorp/hcl) would also make this project really appealing.

**Comment by itchyny** [comment]
Please use `gojq --yaml-input --yaml-output .`.

**Comment by teoincontatto** [comment]
I've should have read better the feature list :sweat_smile: 

In any case adding support for the other mentioned formats would be nice.

**Comment by itchyny** [comment]
- I implemented YAML support because YAML is a much popular format in this container age.
- I don't implement XML because it is far different from JSON; there is no 1to1 mapping against JSON.
- Adding TOML might have chance but it is much less popular than YAML. I'll judge it's worth or not later.
- HCL is application specific format and I don't use it, also worries me about major version incompatibility.

Implementing another format support should be judged carefully because it sacrifice the binary size and code complexity. I will carefully investigate the [popularity in industry](https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=yaml%20file,toml%20file,cjson%20file,json5%20file,hcl%20file).

**Comment by teoincontatto** [comment]
XML has no 1to1 mapping but it could be implemented with some transformation like [xq](https://github.com/kislyuk/yq#xml-support) does:

```
$ printf '
<a>
  <b c="1" d="true">
    hola
    <e />
    mundo
    <f>
      <g h="test">
        !
      </g>
    </f>
    $
  </b>
</a>
' | xq .
{
  "a": {
    "b": {
      "@c": "1",
      "@d": "true",
      "e": null,
      "f": {
        "g": {
          "@h": "test",
          "#text": "!"
        }
      },
      "#text": "holamundo$"
    }
  }
}
```

Inner tags and text items transformation could be improved since they lose the order when deserialized. A possible better transformation would be to add an ordering for child elements something like this:

```
{
  "a": {
    "#childs": [ "b" ],
    "b": {
      "#childs": [ "#hola", "e", "#mundo", "f", "#$" ],
      "@c": "1",
      "@d": "true",
      "e": null,
      "f": {
        "#childs": [ "g" ],
        "g": {
          "#childs": [ "#!" ],
          "@h": "test"
        }
      }
    }
  }
}
```

XML is still [very popular](https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=xml%20file,yaml%20file,json%20file,cjson%20file,json5%20file) and wort to be considered.
