### ISSUE TITLE
Integer math looses precision

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#63]
Hi, I noticed some integer arithmetics and some functions seems to convert float

Example:
```sh
$ go run cmd/gojq/main.go -n '(18281289274965207791/2)*2'
18281289274965207000
$ go run cmd/gojq/main.go -n '18281289274965207791 | floor'
18281289274965207000
```

Looking at the code is seems both `big.Int / int` and `big.Int / big.Int` has this issue.

Not sure `floor` is a good example but could be "passthru" i guess? but some others like `sin` etc might be harder?

**Comment by itchyny** [comment]
I don't think it's worth implementing. Firstly, it is an expected behavior that division truncates to float when indivisible. If we need to keep the precision, it requires rational numbers and I'd not implement this. Secondly, all math functions assumes the input float numbers. If you want to make them work with big integers, most of them requires full scratch implementation which does not worth (see [big.Int](https://golang.org/pkg/math/big/#Int)). Some truncating functions (floor, round, nearbyint, ceil, trunc) can return the argument but how is it useful?

**Comment by itchyny** [comment]
Current behavior is consistent that big integers are closed only by addition, subtraction and multiplication. It is unnatural that some of math functions works and others not. There is no action to take against this issue.

**Comment by wader** [comment]
Thanks, think i understand better now. So if integer division was supported (and not compatible with jq) it would be its own operator or division would behave differently depending on operan types?

I can implement it as a custom function if needed i think.

**Comment by itchyny** [comment]
The gojq runtime does not assume usage of big.Rat anyway.

**Comment by itchyny** [comment]
Okay, it seems that I misunderstand your expectation. The operator is floor division (in Python 3). And your implementation of custom function will work. Another way is to use modulo which keeps the precision of big integers.
```sh
❯ gojq -n 'def intdiv($x): (. - . % $x)/$x; 18281289274965207791 | intdiv(2) | . * 2'
18281289274965207790
```

**Comment by wader** [comment]
Thanks, neat solution
