### ISSUE TITLE
List possible completions

### ISSUE THREAD

**Issue by hoshsadiq** [itchyny/gojq#80]
Hi! Is it possible to get a list of all possible next items? E.g. if I json `{"foo": "hello", "bar": {"baz": true}}`, I'd like to generate a list of all possible items that are valid, such as:

- `.foo`
- `.bar`
- `map`
- `join`
- ... other functions

Notice that `.bar.baz` isn't there. If I were to update the so-to-say "starting point" to `.bar`, it would return:

- `.baz`
- `map`
- `join`
- ... other functions

Reason for this is that I want to try my hand at #74, so I want to use see if auto completion can be created based on the json itself. This will be as part of the library rather than anything else.

**Comment by itchyny** [comment]
Listing next possible tokens is a hard problem in general because it it tightly coupled with the syntax, lexer, parser, as well as executors. When user defines some filters the completion should list them within their scopes. Filter arities are also related to this topic; no `(` follows after `to_entries` filter (but it does when user defined their own `to_entries/1`). I don't have plan to provide such complex and unmaintainable feature from this library. Instead, you can simply list map keys, track parenthesis, and use `builtins` to list internal functions.

**Comment by hoshsadiq** [comment]
Great! That seems reasonable enough. Thanks.
